### ISSUE TITLE
This doesn't works

### ISSUE THREAD

**Issue by Vaibhav-Naik-1** [AmitKumarHQ/Discord.js-Info-Command#1]
Which `discord.js` version is this?
and you can provide `pacakge.json` ,that is important. `pacakge-lock.json` and `node_modules` are not required.
the `info.js` cmd , there is nothing like `userType` and `serverType` , there is only `channelType`
This code won't work , never ever.

Can you please explain me?
does it works for you? then send a video of getting a info about a server

**Comment by AmitKumarHQ** [comment]
This code was made for Discord.js v13, but I will be releasing the v14 code soon.
The code is arranged as per most bot's project structure, and if not then you can definitely figure it out by just looking at the code.

This is just a working example. If you know what you are doing then you will be able to implement it in your bot without any issues.

**Comment by Vaibhav-Naik-1** [comment]
Ok , nice you are making v14 also, make another repo for it.

But in the `info.js`  , in options you have written `serverTypes: ['GUILD']`, can you explain me that? in the [docs](https://discord.js.org/#/docs/discord.js/13.9.1/typedef/ApplicationCommandOption) there is no `serverType` and userType` 
Ok forget about `userType` ,  tell me `serverType` huh?
